//! AGENTS.md renderer — generates project instruction markdown from analysis data.

use crate::analyzer::Analysis;
use crate::scanner::ScannedProject;

/// Generate the full AGENTS.md content from analysis and scan data.
///
/// This function produces a structured markdown document with:
/// - Project overview and language detection
/// - Build systems, test frameworks, linting tools
/// - Code conventions and best practices
/// - Commands reference
pub fn generate_agents_md(analysis: &Analysis, project: &ScannedProject) -> String {
    let mut md = String::new();

    // ── Header ────────────────────────────────────────────────────────────
    md.push_str("# Project Instructions\n\n");
    md.push_str("> Auto-generated by `xai-grok-init`.\n\n");

    // ── Overview ──────────────────────────────────────────────────────────
    md.push_str("## Overview\n\n");
    md.push_str(&format!(
        "- **Repository root**: `{}`\n",
        project.root.display()
    ));
    if !project.top_level_dirs.is_empty() {
        md.push_str(&format!(
            "- **Top-level directories**: {}\n",
            project.top_level_dirs.join(", ")
        ));
    }
    md.push('\n');

    // ── Languages ─────────────────────────────────────────────────────────
    if !analysis.languages.is_empty() {
        md.push_str("## Detected Languages\n\n");
        for lang in &analysis.languages {
            md.push_str(&format!("- {}\n", lang.as_str()));
        }
        md.push('\n');
    }

    // ── Build System ──────────────────────────────────────────────────────
    if let Some(bs) = &analysis.build_system {
        md.push_str("## Build System\n\n");
        md.push_str(&format!("- **{0}**: `{1}`\n", bs.as_str(), bs.build_command()));
        md.push('\n');
    }

    // ── Test Frameworks ───────────────────────────────────────────────────
    if !analysis.test_frameworks.is_empty() {
        md.push_str("## Test Frameworks\n\n");
        for tf in &analysis.test_frameworks {
            md.push_str(&format!("- **{0}**: `{1}`\n", tf.as_str(), tf.test_command()));
        }
        md.push('\n');
    }

    // ── Linters / Formatters ─────────────────────────────────────────────
    if !analysis.linter_formatters.is_empty() {
        md.push_str("## Linters & Formatters\n\n");
        for lf in &analysis.linter_formatters {
            if let Some(cmd) = lf.lint_command() {
                md.push_str(&format!("- **{}**: `{}`\n", lf.as_str(), cmd));
            } else {
                md.push_str(&format!("- **{}** (formatter)\n", lf.as_str()));
            }
        }
        md.push('\n');
    }

    // ── Frameworks ────────────────────────────────────────────────────────
    if !analysis.frameworks.is_empty() {
        md.push_str("## Frameworks\n\n");
        for fw in &analysis.frameworks {
            md.push_str(&format!("- {}\n", fw));
        }
        md.push('\n');
    }

    // ── Commands Reference ────────────────────────────────────────────────
    let cmds = &analysis.commands;
    if !cmds.build.is_empty() || !cmds.test.is_empty() || !cmds.lint.is_empty() {
        md.push_str("## Commands\n\n");

        if !cmds.build.is_empty() {
            md.push_str("### Build\n\n");
            for cmd in &cmds.build {
                md.push_str(&format!("- `{}`\n", cmd));
            }
            md.push('\n');
        }

        if !cmds.test.is_empty() {
            md.push_str("### Test\n\n");
            for cmd in &cmds.test {
                md.push_str(&format!("- `{}`\n", cmd));
            }
            md.push('\n');
        }

        if !cmds.lint.is_empty() {
            md.push_str("### Lint\n\n");
            for cmd in &cmds.lint {
                md.push_str(&format!("- `{}`\n", cmd));
            }
            md.push('\n');
        }
    }

    // ── Conventions ───────────────────────────────────────────────────────
    if !analysis.conventions.is_empty() {
        md.push_str("## Conventions\n\n");
        for conv in &analysis.conventions {
            let emoji = match conv.certainty {
                crate::analyzer::Certainty::High => "🔴",
                crate::analyzer::Certainty::Medium => "🟡",
                crate::analyzer::Certainty::Low => "🟢",
            };
            md.push_str(&format!("- {} {}\n", emoji, conv.description));
        }
        md.push('\n');
    }

    // ── Monorepo ──────────────────────────────────────────────────────────
    if analysis.monorepo {
        md.push_str("## Monorepo Structure\n\n");
        md.push_str("This is a monorepo. Scope changes to the relevant package.\n\n");
    }

    // ── Source directories ────────────────────────────────────────────────
    if !analysis.source_dirs.is_empty() {
        md.push_str("## Source Directories\n\n");
        for dir in &analysis.source_dirs {
            md.push_str(&format!("- `{}`\n", dir));
        }
        md.push('\n');
    }

    md
}
