//! Renderers for `.grok/AGENTS.md` and `.grok/config.toml`.
//!
//! Generates structured markdown and TOML from scan + analysis data.

use crate::analyzer::{Analysis, BuildSystem, Certainty};
use crate::scanner::ScannedProject;

/// Generate the full `.grok/AGENTS.md` content with YAML frontmatter.
pub fn generate_grok_agents_md(analysis: &Analysis, project: &ScannedProject) -> String {
    let project_name = infer_project_name(project);
    let project_desc = infer_project_description(project, analysis);
    let model = infer_preferred_model(analysis);

    let mut md = String::new();

    // ── Frontmatter ─────────────────────────────────────────────────────
    md.push_str("---\n");
    md.push_str(&format!("name: {}\n", project_name));
    md.push_str(&format!("description: {}\n", project_desc));
    md.push_str(&format!("model: {}\n", model));
    md.push_str("---\n\n");

    // ── Header ──────────────────────────────────────────────────────────
    md.push_str(&format!("# {} — Project Instructions\n\n", project_name));
    md.push_str(
        "> Generated by `/init`. Edit this file to guide how AI agents work with this project.\n\n",
    );

    // ── Overview ────────────────────────────────────────────────────────
    md.push_str("## Overview\n\n");
    md.push_str(&format!(
        "- **Repository root**: `{}`\n",
        project.root.display()
    ));
    if !analysis.languages.is_empty() {
        let lang_names: Vec<&str> = analysis.languages.iter().map(|l| l.as_str()).collect();
        md.push_str(&format!("- **Languages**: {}\n", lang_names.join(", ")));
    }
    if let Some(bs) = &analysis.build_system {
        md.push_str(&format!("- **Build system**: {}\n", bs.as_str()));
    }
    if !analysis.test_frameworks.is_empty() {
        let tf_names: Vec<&str> = analysis
            .test_frameworks
            .iter()
            .map(|t| t.as_str())
            .collect();
        md.push_str(&format!("- **Test frameworks**: {}\n", tf_names.join(", ")));
    }
    if analysis.monorepo {
        md.push_str("- **Structure**: Monorepo\n");
    }
    if !project.top_level_dirs.is_empty() {
        md.push_str(&format!(
            "- **Top-level directories**: {}\n",
            project.top_level_dirs.join(", ")
        ));
    }
    md.push('\n');

    // ── Project Structure ───────────────────────────────────────────────
    if !analysis.source_dirs.is_empty() {
        md.push_str("## Project Structure\n\n");
        md.push_str("Key source directories:\n\n");
        for dir in &analysis.source_dirs {
            md.push_str(&format!("- `{}`\n", dir));
        }
        md.push('\n');
    }

    // ── Commands ────────────────────────────────────────────────────────
    let cmds = &analysis.commands;
    if !cmds.build.is_empty() || !cmds.test.is_empty() || !cmds.lint.is_empty() {
        md.push_str("## Commands\n\n");

        if !cmds.build.is_empty() {
            md.push_str("### Build\n\n");
            for cmd in &cmds.build {
                md.push_str(&format!("- `{}`\n", cmd));
            }
            md.push('\n');
        }

        if !cmds.test.is_empty() {
            md.push_str("### Test\n\n");
            for cmd in &cmds.test {
                md.push_str(&format!("- `{}`\n", cmd));
            }
            md.push('\n');
        }

        if !cmds.lint.is_empty() {
            md.push_str("### Lint\n\n");
            for cmd in &cmds.lint {
                md.push_str(&format!("- `{}`\n", cmd));
            }
            md.push('\n');
        }
    }

    // ── Frameworks ──────────────────────────────────────────────────────
    if !analysis.frameworks.is_empty() {
        md.push_str("## Frameworks\n\n");
        for fw in &analysis.frameworks {
            md.push_str(&format!("- {}\n", fw));
        }
        md.push('\n');
    }

    // ── Conventions ─────────────────────────────────────────────────────
    if !analysis.conventions.is_empty() {
        md.push_str("## Conventions\n\n");
        for conv in &analysis.conventions {
            let emoji = match conv.certainty {
                Certainty::High => "🔴",
                Certainty::Medium => "🟡",
                Certainty::Low => "🟢",
            };
            md.push_str(&format!("- {} {}\n", emoji, conv.description));
        }
        md.push('\n');
    }

    md
}

/// Generate `.grok/config.toml` from analysis data.
pub fn generate_grok_config(analysis: &Analysis, project: &ScannedProject) -> String {
    let mut toml = String::new();
    toml.push_str("# Generated by `/init` — xai-grok-init\n");
    toml.push_str("# Project-level configuration for Grok Build\n\n");

    // ── Permission section ──────────────────────────────────────────────
    toml.push_str("[permission]\n");
    toml.push_str("allow = [\n");

    // Always allow basic tools
    toml.push_str("    \"Read\",\n");
    toml.push_str("    \"Grep\",\n");
    toml.push_str("    \"Edit\",\n");
    toml.push_str("    \"Write\",\n");

    // Allow build command for the detected build system
    if let Some(bs) = &analysis.build_system {
        match bs {
            BuildSystem::Cargo => {
                toml.push_str("    \"Bash(cargo *)\",\n");
            }
            BuildSystem::Npm | BuildSystem::Pnpm | BuildSystem::Yarn | BuildSystem::Bun => {
                toml.push_str("    \"Bash(npm *)\",\n");
                toml.push_str("    \"Bash(npx *)\",\n");
            }
            BuildSystem::Pip | BuildSystem::Poetry | BuildSystem::Uv => {
                toml.push_str("    \"Bash(pip *)\",\n");
                toml.push_str("    \"Bash(python *)\",\n");
            }
            BuildSystem::GoBuild => {
                toml.push_str("    \"Bash(go *)\",\n");
            }
            BuildSystem::Make => {
                toml.push_str("    \"Bash(make *)\",\n");
            }
            _ => {
                toml.push_str("    \"Bash(*)\",\n");
            }
        }
    }

    // Only allow git if it's a git repo
    if project.is_worktree || project.root.join(".git").exists() {
        toml.push_str("    \"Bash(git *)\",\n");
    }

    toml.push_str("]\n\n");

    // ── MCP Servers section ─────────────────────────────────────────────
    toml.push_str("[mcp_servers]\n");
    toml.push_str("# Add project-specific MCP servers here.\n");
    toml.push_str("# Example:\n");
    toml.push_str("# [mcp_servers.my-db]\n");
    toml.push_str("#   command = \"npx\"\n");
    toml.push_str("#   args = [\"-y\", \"@modelcontextprotocol/server-postgres\", \"--connection\", \"postgresql://...\"]\n\n");

    // ── Plugins section ─────────────────────────────────────────────────
    toml.push_str("[plugins]\n");
    toml.push_str("# Add project-specific plugins here.\n");
    toml.push_str("# Example:\n");
    toml.push_str("# [plugins.superpowers]\n");
    toml.push_str("#   skills = [\"brainstorming\", \"test-driven-development\"]\n");

    toml
}

// ─── Legacy: root AGENTS.md ────────────────────────────────────────────────

/// Generate the full AGENTS.md content from analysis and scan data (legacy root format).
pub fn generate_agents_md(analysis: &Analysis, project: &ScannedProject) -> String {
    // Delegate to the new format but without frontmatter
    let mut md = String::new();
    md.push_str("# Project Instructions\n\n");
    md.push_str("> Auto-generated by `xai-grok-init`.\n\n");
    md.push_str("> **Note**: Consider running `/init` (without arguments) to regenerate into `.grok/AGENTS.md`\n");
    md.push_str("> which supports frontmatter and is the recommended location.\n\n");

    // Reuse structure from grok_agents_md minus frontmatter
    let grok = generate_grok_agents_md(analysis, project);

    // Strip frontmatter (everything between first --- and second ---)
    let body = if let Some(end) = grok.splitn(3, "---\n").nth(2) {
        end
    } else {
        &grok
    };

    md.push_str(body);
    md
}

// ─── Helpers ───────────────────────────────────────────────────────────────

fn infer_project_name(project: &ScannedProject) -> String {
    // Try manifest names first
    for manifest in &project.manifests {
        match manifest {
            crate::scanner::Manifest::CargoToml { name, .. }
            | crate::scanner::Manifest::PackageJson { name, .. } => {
                if !name.is_empty() {
                    return name.clone();
                }
            }
            crate::scanner::Manifest::GoMod { module, .. } => {
                if let Some(simple) = module.split('/').last() {
                    if !simple.is_empty() {
                        return simple.to_string();
                    }
                }
                return module.clone();
            }
            crate::scanner::Manifest::PyProjectToml { name: Some(n), .. } => {
                if !n.is_empty() {
                    return n.clone();
                }
            }
            _ => {}
        }
    }

    // Fallback: directory name
    project
        .root
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("my-project")
        .to_string()
}

fn infer_project_description(project: &ScannedProject, analysis: &Analysis) -> String {
    // Try README first line
    for readme in &project.readme_files {
        for line in readme.content.lines() {
            let trimmed = line.trim();
            if !trimmed.is_empty() && !trimmed.starts_with('#') && !trimmed.starts_with('[') {
                let desc = trimmed.trim_matches(|c: char| c == '>' || c == '*' || c == '_');
                if !desc.is_empty() && desc.len() < 200 {
                    return desc.to_string();
                }
            }
        }
    }

    // Build from analysis
    let lang_names: Vec<&str> = analysis.languages.iter().map(|l| l.as_str()).collect();
    let langs = if lang_names.is_empty() {
        "unknown".to_string()
    } else {
        lang_names.join(", ")
    };

    let bs = analysis
        .build_system
        .as_ref()
        .map(|b| b.as_str().to_string())
        .unwrap_or_default();

    if !bs.is_empty() {
        format!("A {} project using {}.", langs, bs)
    } else {
        format!("A {} project.", langs)
    }
}

fn infer_preferred_model(_analysis: &Analysis) -> String {
    // Default to grok-build for project work
    // Future: could infer from project type (e.g., big model for complex code)
    "grok-build".to_string()
}
